"""revision attribute password

Revision ID: 2819476b97fe
Revises: c2b08f29e7e1
Create Date: 2023-06-08 19:58:36.583445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2819476b97fe'
down_revision = 'c2b08f29e7e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
