"""revision attribute password

Revision ID: 557b720a8da2
Revises: 2819476b97fe
Create Date: 2023-06-08 19:59:15.273749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557b720a8da2'
down_revision = '2819476b97fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
