"""add date

Revision ID: c2b08f29e7e1
Revises: a400f98df5e7
Create Date: 2023-06-07 22:23:58.539876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b08f29e7e1'
down_revision = 'a400f98df5e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'date_created')
    # ### end Alembic commands ###
