"""add short link

Revision ID: e644593789db
Revises: 557b720a8da2
Create Date: 2023-06-08 21:43:29.738667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e644593789db'
down_revision = '557b720a8da2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=200), nullable=True),
    sa.Column('secret_key', sa.VARCHAR(length=200), nullable=True),
    sa.Column('target_url', sa.VARCHAR(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_link_key'), 'short_link', ['key'], unique=True)
    op.create_index(op.f('ix_short_link_secret_key'), 'short_link', ['secret_key'], unique=True)
    op.create_index(op.f('ix_short_link_target_url'), 'short_link', ['target_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_link_target_url'), table_name='short_link')
    op.drop_index(op.f('ix_short_link_secret_key'), table_name='short_link')
    op.drop_index(op.f('ix_short_link_key'), table_name='short_link')
    op.drop_table('short_link')
    # ### end Alembic commands ###
